<a href="https://colab.research.google.com/github/jeff-ai-ml/ai-python-basic-programs/blob/main/numpy_programs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#create a one dimentional array (rank1 tenser) from the list of elements

import numpy as np

l = [4,3,5,7,8]

arr = np.array(l)

print(arr)

print(arr.shape)

print(arr.ndim)

[4 3 5 7 8]
(5,)
1


In [11]:
#🔹 2. Create arrays of zeros, ones, and a constant

zeros = np.zeros((2,3))
ones = np.ones((3,4))
fives = np.full((2,4), 5)

print(zeros)
print(ones)
print(fives)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[5 5 5 5]
 [5 5 5 5]]


In [14]:
#🔹 3. Create an array of even numbers from 2 to 20

evens = np.arange(2,21,2)

print(evens)

[ 2  4  6  8 10 12 14 16 18 20]


In [19]:
#🔹 4. Reshape a 1D array into a 2D array

arr = np.arange(1,13, 1)

print(arr)

arr_reshape = arr.reshape(3,4)

print(arr_reshape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
